FROM node:20-alpine
ENV NODE_ENV=development

WORKDIR /app
COPY ["package.json", "./"]

RUN npm install --production --silent && mv node_modules ../
COPY . .

ENV NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN='ohmybackend.firebaseapp.com'
ENV NEXT_PUBLIC_FIREBASE_PROJECT_ID='ohmybackend'
ENV NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET='ohmybackend.appspot.com'
ENV NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID='67917237882'
ENV NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID='G-TPXGWFTYSD'

ENV NEXT_PUBLIC_FIREBASE_APP_ID=$NEXT_PUBLIC_FIREBASE_APP_ID
ENV NEXT_PUBLIC_FIREBASE_API_KEY=$NEXT_PUBLIC_FIREBASE_API_KEY
ENV NEXT_PUBLIC_NEWS_APIKEY=$NEXT_PUBLIC_NEWS_APIKEY


EXPOSE 3000
RUN chown -R node /app
USER node
CMD ["npm", "run", "dev"]
