version: '3.4'

services:
  filteredv2:
    image: filteredv2
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_FIREBASE_API_KEY: $NEXT_PUBLIC_FIREBASE_API_KEY
      NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ohmybackend.firebaseapp.com
      NEXT_PUBLIC_FIREBASE_PROJECT_ID: ohmybackend
      NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ohmybackend.appspot.com
      NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: 67917237882
      NEXT_PUBLIC_FIREBASE_APP_ID: $NEXT_PUBLIC_FIREBASE_APP_ID
      NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: G-TPXGWFTYSD
      NEXT_PUBLIC_NEWS_APIKEY: $NEXT_PUBLIC_NEWS_APIKEY
    ports:
      - 4001:3000
