apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: filtered-svc
  name: filtered-svc
spec:
  ports:
  - name: 3000-4001
    port: 3000
    protocol: TCP
    targetPort: 4001
  selector:
    app: filtered-svc
  type: NodePort
status:
  loadBalancer: {}
