apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: filtered-web
  name: filtered-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: filtered-web
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: filtered-web
    spec:
      containers:
      - image: siddhantprateek/filtered
        name: filteted
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: filtered-config
        resources: {}
status: {}
